### ISSUE TITLE
DJANGO SETTINGS

### ISSUE THREAD

**Issue by essymanyeki16** [qlands/FormShare#13] opened 2016-12-16 09:08 UTC
SECRET-KEY cannot be empty. I need to resolve this

**Comment by qlands** [comment] 2017-01-15 18:34
Please post an screen-shot of the problem and more information

**Comment by essymanyeki16** [comment] 2017-06-17 10:39
Great product. Just this error. 
[django error.odt.tar.gz](https://github.com/qlands/FormShare/files/1082490/django.error.odt.tar.gz)

**Comment by essymanyeki16** [comment] 2017-06-17 10:41
This error comes every time i restart my machine after a successful installation.

**Comment by qlands** [comment] 2017-06-20 07:29
This has been reported [elsewhere](https://www.google.it/search?q=django+the+SECRET_KEY+setting+must+not+be+empty.&ie=utf-8&oe=utf-8&client=firefox-b&gfe_rd=cr&ei=s8xIWd3bK7DBXvGWo4gE) and might be caused by different things. 

Try removing the compiled files pyc.
`find . -name "*.pyc" -exec rm -rf {} \;`
 
Sorry for the inconvenience

**Comment by qlands** [comment] 2017-06-21 09:50
Also, every time you test the server after a restart you need:

Activate the environment then:

export PYTHONPATH=$PYTHONPATH:/opt/formshare/src/formshare
export DJANGO_SETTINGS_MODULE=formshare.settings.default_settings
python manage.py runserver

**Comment by essymanyeki16** [comment] 2018-03-26 12:50
The last suggestion worked for me

**Comment by essymanyeki16** [comment] 2018-03-27 08:17
But now the error is back again. You need to sort this once and for all.

**Comment by qlands** [comment] 2019-10-01 00:54
Closing this because FormShare 2.0 has been released. 1.0 is no longer maintained.

**Closed by qlands** 2019-10-01 00:54 UTC
